### PR TITLE
PHP 8 Support

### LINKED ISSUE #64: PHP 8 compatibility
Please make it compatible with PHP 8/8.1

### PR DESCRIPTION
**Pull request by Numkil**
### Added
 
PHP 8 Support. All tests are green. I will be testing within my own project more thoroughly next week but its a good start :) 

Obviously would need to be a new major release.

Fixes #64

### CODE REVIEW

**Comment by Numkil** [comment]
@LucWollants 
fyi

**Comment by zuuperman** [comment]
We started 2 weeks ago as preparation for a D10 upgrade. We managed to get it PHP supported, but switched to another JMS repository as quickfix.

I'll check tomorrow with my colleague which version we will use.
I saw you changed the geopoint test to use strings. We changed the value object to request float, as latitude and longitude are floats.

**Comment by Numkil** [comment]
@zuuperman I wasn't aware I changed any test expectations? Could you point me to where i have done that? As far as I can see the text expecations should be identical to what they are currently in main.

**Comment by Numkil** [comment]
I've got this running in our project now and it seems to work without any issues. Which i kind of expected seeing all tests pass on php8.

**Review by zuuperman — APPROVED** [review]

**Comment by Numkil** [comment]
awesome thank you @zuuperman 👍

**Pull request closed without merging**
